namespace ImpostorHqR.Extension.Api.Interface.Web.Page.Api.Graph
{
    public interface IGraphPageProvider
    {
        /// <summary>
        /// This function will slice and splice code in order to create a graph page that will be automatically registered and ready to use.
        /// </summary>
        /// <param name="graphs">Graphs, generated by the IGraphProvider</param>
        /// <param name="title">The title of the page.</param>
        /// <param name="handle">The effective path to register.</param>
        /// <param name="widthPercent">The width of the graphs (10-100).</param>
        /// <returns></returns>
        public IGraphPage Create(IGraph[] graphs, string title, string handle, byte widthPercent);
    }
}
